### PR TITLE
feat: gradebook main container classname

### PR DESCRIPTION
**Pull request by vlasovmichael**
- Added the ability to manage styles through the main container like in "frontend-app-account" or "frontend-app-profile"

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @vlasovmichael! I've created [OSPR-6432](https://openedx.atlassian.net/browse/OSPR-6432) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@vlasovmichael Thank you for your contribution. I will line this up for our review.

**Comment by vlasovmichael** [comment]
> @vlasovmichael Thank you for your contribution. I will line this up for our review.

Thanks. Fixed snapshot tests

**Review by muselesscreator — APPROVED** [review]
Seems reasonable to me

**Comment by natabene** [comment]
@muselesscreator Once tests are pass, can you merge? Community authors usually run tests or merge.

**Comment by edx-webhook** [comment]
@vlasovmichael 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-gradebook&entry.867055334=https://github.com/openedx/frontend-app-gradebook/pull/226&entry.1484655318=https://github.com/vlasovmichael&entry.752974735=2022-02-02+11:29&entry.1917517419=2022-02-07+20:22&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
