### PR TITLE
build: use shared browserslist config 

### PR DESCRIPTION
**Pull request by Jawayria**
Removes custom browserslist configuration in favor of using a [shared configuration](https://github.com/edx/browserslist-config).
This change reduces the resultant asset bundle size.

### CODE REVIEW

**Review by UsamaSadiq — APPROVED** [review]

**Comment by Jawayria** [comment]
Frontend Bom will be carrying these forward.
cc: @abdullahwaheed

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Jawayria!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

**Comment by natabene** [comment]
This looks like an internal PR, is anyone working on this?

**Comment by abdullahwaheed** [comment]
@natabene yes @Mashal-m is part of @openedx/fed-bom and we are working on this PR. Once her credentials are created, we'll proceed further

**Comment by natabene** [comment]
@abdullahwaheed Great. Please note that @Mashal-m will need to be onboarded by the 2U HelpDesk, so she doesn't need to sign the CLA. Please work with 2U HelpDesk to expedite the process.
Also, this PR will forever be flagged anyway, if original author is no longer working for 2U. So you can either just override and merge regardless, if you can. If not, @Mashal-m will need to re-open this work in a new PR under her name, once she has been onboarded by HelpDesk.

**Comment by openedx-webhooks** [comment]
@Jawayria Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-gradebook&entry.867055334=https://github.com/openedx/frontend-app-gradebook/pull/243&entry.1484655318=https://github.com/Jawayria&entry.752974735=2022-06-03+15:56&entry.1917517419=2022-10-05+12:52&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
