### PR TITLE
chore: adds renovate.json

### PR DESCRIPTION
**Pull request by farhaanbukhsh**

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @farhaanbukhsh! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by farhaanbukhsh** [comment]
@feanil can I get an approval here, thanks :)

**Comment by salman2013** [comment]
@farhaanbukhsh there is already one [PR](https://github.com/openedx/frontend-app-gradebook/pull/392) merged to add renovate.json file in this repository if there is any update then I think you can update the existing renovate.json file.

**Comment by feanil** [comment]
@farhaanbukhsh the renovate.json can be put in a bunch of different locations: https://docs.renovatebot.com/configuration-options/

**Comment by farhaanbukhsh** [comment]
@feanil @salman2013  thanks

**Comment by openedx-webhooks** [comment]
@farhaanbukhsh Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-gradebook&entry.867055334=https://github.com/openedx/frontend-app-gradebook/pull/395&entry.1484655318=https://github.com/farhaanbukhsh&entry.752974735=2024-05-23+09:13&entry.1917517419=2024-05-23+19:18&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
