### PR TITLE
feat: gradebook main container classname

### PR DESCRIPTION
**Pull request by vlasovmichael**
**Description:**
Backport PR https://github.com/openedx/frontend-app-gradebook/pull/226 to `open-release/maple.master`.

- Added the ability to manage styles through the main container like in "frontend-app-account" or "frontend-app-profile"

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @vlasovmichael! I've created [OSPR-6446](https://openedx.atlassian.net/browse/OSPR-6446) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by cmltaWt0 — APPROVED** [review]

**Comment by cmltaWt0** [comment]
@openedx-community-bot merge

**Comment by cmltaWt0** [comment]
@muselesscreator It seems like this this app doesn't have community bot merge workflow.
Could you merge it too? Thanks!

**Comment by natabene** [comment]
@vlasovmichael Thank you for your contribution.

**Pull request merged**
