### PR TITLE
fix: fix sidebar scrolling and adaptation for mobile

### PR DESCRIPTION
**Pull request by ihor-romaniuk**
**TL;DR -**

This pull request contains minor fixes related to the responsiveness of the blocks for mobile phones. All the before and after screenshots are below.

**Related Pull Requests**
PR to the master branch: https://github.com/openedx/frontend-app-gradebook/pull/363
PR to the open-release/quince.master branch: https://github.com/openedx/frontend-app-gradebook/pull/370

**What changed?**
- fixed text overload in the title when the course ID is too long

|  Before |  After |
|---|---|
|  image |  image |

- fixed appearance and scrolling of the sidebar

|  Before |  After |
|---|---|
|  image |  image |
|   image  |   image |

- Fixed adaptation of the search and filter buttons on mobile phones.

|  Before |  After |
|---|---|
|  image |  image |

- removed excess empty space under the main table of contents

|  Before |  After |
|---|---|
|  image |  image |

- fix adaptation modal content to mobile view

|  Before |  After |
|---|---|
|  image  |  image |

**Developer Checklist**
- [ ] Test suites passing
- [ ] Documentation and test plan updated, if applicable
- [ ] Received code-owner approving review
- [ ] Bumped version number [package.json](../package.json)

**Reviewer Checklist**

Collectively, these should be completed by reviewers of this PR:

- [ ] I've done a visual code review
- [ ] I've tested the new functionality

FYI: @openedx/content-aurora

### CODE REVIEW

**Comment by mphilbrick211** [comment]
Apologies for the ping @arbrandes , it looks like this needs product review.

**Comment by jmakowski1123** [comment]
These fixes look great, thanks for contributing! This has product review.

**Review by arbrandes — APPROVED** [review]
Master is approved, so is this.

**Comment by openedx-webhooks** [comment]
@ihor-romaniuk 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-gradebook&entry.867055334=https://github.com/openedx/frontend-app-gradebook/pull/362&entry.1484655318=https://github.com/ihor-romaniuk&entry.752974735=2023-10-23+13:12&entry.1917517419=2024-04-03+18:28&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
