### PR TITLE
feat: enabling header override

### PR DESCRIPTION
**Pull request by jfavellar90**
**What changed?**

This PR adds `frontend-component-header` as a dependency in the Gradebook MFE and inserts this component to replace the default Gradebook header. It enables the header override for styling/theming purposes. A couple of notes about this change:

- The `frontend-component-header` version used is 2.2.5 to get compatibility with the current Gradebook state. `frontend-component-footer` version is updated to the latest available since it does not have compatibility issues.
- The `AppProvider` component from `frontend-platform` replaces the regular `provider` component in the MFE so the application has the context of the logged-in user and renders the header properly.
-  Some tests were adjusted based on these changes.

**Screenshots**:

Screenshot from 2021-12-16 09-00-18

**Responsive**

Screenshot from 2021-12-16 09-01-07

**Developer Checklist**
- [ ] Test suites passing
- [ ] Documentation and test plan updated, if applicable
- [ ] Received code-owner approving review
- [ ] Bumped version number [package.json](../package.json)

**Testing Instructions**

There's no particular action to perform when testing this feature. Just run the MFE with this branch and check the header is rendered as expected

**Reviewer Checklist**

Collectively, these should be completed by reviewers of this PR:

- [ ] I've done a visual code review
- [ ] I've tested the new functionality

FYI: @edx/masters-devs-gta

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @jfavellar90! I've created [OSPR-6287](https://openedx.atlassian.net/browse/OSPR-6287) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by natabene** [comment]
@jfavellar90 Thank you for your contribution. Is this ready for our review?

**Comment by jfavellar90** [comment]
@natabene yes, it is ready

**Review by muselesscreator — APPROVED** [review]
LGTM

**Comment by edx-webhook** [comment]
@jfavellar90 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/frontend-app-gradebook&entry.867055334=https://github.com/edx/frontend-app-gradebook/pull/220&entry.1484655318=https://github.com/jfavellar90&entry.752974735=2021-12-16+04:59&entry.1917517419=2021-12-21+15:40&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
