### PR TITLE
fix: fix loss of field focus after each character for search field

### PR DESCRIPTION
**Pull request by ihor-romaniuk**
**TL;DR -** Fixed loss of field focus after each character for the search field.
The cause of the problem is the last requirements upgrade for the paragon package from `14.16.4` to `19.6.0`. In the paragon library, the `SearchField` was significantly changed and currently after every key press it losses the field focus.

FYI: @openedx/content-aurora

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ihor-romaniuk!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@ihor-romaniuk Thank you for the contribution. It looks like this is ready for our review, correct?

**Comment by ihor-romaniuk** [comment]
> @ihor-romaniuk Thank you for the contribution. It looks like this is ready for our review, correct?

Yes, everything is ready for review.

**Comment by arbrandes** [comment]
frontend-app-library-authoring has been affected by this issue forever - gonna try this fix there, too.  I'll approve once I confirm it fixes it (here and there).  Thanks a lot!

**Comment by leangseu-edx** [comment]
Hi, thank you for contributing. 

May I ask, why is there a change for `package-lock.json` when `package.json` isn't? There was a fix a did a while back for this, without the need to change that. I will bring this to the team and should be able to approve it later today. https://github.com/openedx/frontend-app-gradebook/commit/d55abbe91ea87c4225e81c1d05bff89b91727a1a

**Comment by ihor-romaniuk** [comment]
> Hi, thank you for contributing.
> 
> May I ask, why is there a change for `package-lock.json` when `package.json` isn't? There was a fix a did a while back for this, without the need to change that [d55abbe](https://github.com/openedx/frontend-app-gradebook/commit/d55abbe91ea87c4225e81c1d05bff89b91727a1a). I will bring this to the team and should be able to approve it later today.

all checks fell when installing npm and after rebuilding the package-log all checks went through correctly

**Review by muselesscreator — APPROVED** [review]
LGTM

**Comment by muselesscreator** [comment]
Thank you for the clean tests :-)

**Comment by openedx-webhooks** [comment]
@ihor-romaniuk 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-gradebook&entry.867055334=https://github.com/openedx/frontend-app-gradebook/pull/262&entry.1484655318=https://github.com/ihor-romaniuk&entry.752974735=2022-09-12+12:40&entry.1917517419=2022-12-05+16:56&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
