### PR TITLE
[BD-46] feat: added Paragon translations and LANGUAGE_PREFERENCE_COOKIE_NAME

### PR DESCRIPTION
**Pull request by peterkulko**
Issue: https://github.com/openedx/frontend-app-gradebook/issues/340

**What changed?**

- Ensure paragonMessages gets passed to the initialization so the hardcoded English strings throughout Paragon components use translations instead.

**Developer Checklist**
- [x] Test suites passing
- [ ] Documentation and test plan updated, if applicable
- [x] Received code-owner approving review
- [ ] Bumped version number [package.json](../package.json)

**Testing Instructions**

[ How should a reviewer test this PR? ]

**Reviewer Checklist**

Collectively, these should be completed by reviewers of this PR:

- [ ] I've done a visual code review
- [ ] I've tested the new functionality

FYI: @openedx/content-aurora

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @PKulkoRaccoonGang!


When this pull request is ready, tag your edX technical lead.

**Comment by PKulkoRaccoonGang** [comment]
@adamstankiewicz looks like Frontend App Gradbook didn't have the required variable in `LANGUAGE_PREFERENCE_COOKIE_NAME='openedx-language-preference' `and the translations didn't work.

**Review by monteri — APPROVED** [review]

**Review by adamstankiewicz — APPROVED** [review]
LGTM! Good catch on the `LANGUAGE_PREFERENCE_COOKIE_NAME`. FWIW (as a sanity check), for 2U/edX deployments of this MFE, the missing `LANGUAGE_PREFERENCE_COOKIE_NAME` was a non-issue in stage/production as our internal configuration sets this setting as a common environment variable applicable to all MFEs.

Definitely should be there for local dev though!

**Comment by openedx-webhooks** [comment]
@PKulkoRaccoonGang 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-gradebook&entry.867055334=https://github.com/openedx/frontend-app-gradebook/pull/341&entry.1484655318=https://github.com/PKulkoRaccoonGang&entry.752974735=2023-07-06+11:14&entry.1917517419=2023-07-15+14:44&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
