### PR TITLE
[🫒 backport] fix: use getConfig in order to support runtime configuration

### PR DESCRIPTION
**Pull request by kdmccormick**
Backport of https://github.com/openedx/frontend-app-gradebook/pull/286. Please use that PR for details & discussion.

### CODE REVIEW

**Comment by arbrandes** [comment]
Why does that test fail here, but not in master?  Weird.

**Comment by kdmccormick** [comment]
@arbrandes only because I haven't updated this PR with Ghassan's fix yet 😛

**Comment by kdmccormick** [comment]
Pushed an updated commit, `npm test` should pass now...

**Comment by kdmccormick** [comment]
@arbrandes Thanks for the review on the master PR! This one's ready for you too.

**Review by muselesscreator — APPROVED** [review]
LGTM

**Pull request merged**
